### ISSUE TITLE
Datenmanipulation 6.3 Rechtschreibefehler 

### ISSUE THREAD

**Issue by chrigorion** [dxiai/daten-organisation#87]
Weil nach einer Datenmanipulation die ursprünglichen Daten nicht mehr eindeutig reproduziert werden können, lassen sich die Ergebnisse nicht mehr bestätigen oder wiederlegen. Das kommt einem vollständigen Datenverlust gleich, denn alle vorliegenden Daten können manipuliert worden sein.

Keine Datenreproduktion möglich
Wird eine Datenmanipulation entdeckt oder ist eine Manipulation sehr wahrscheinlich, dann ist es nicht mehr möglich, die ursprünglichen Daten zu reproduzieren. In diesem Fall gelten alle Daten eines Datensatzes als **komprimitiert.** Solche Daten dürfen auf keinen Fall für Analysen weiterverwendet werden.

Korrekt wäre **kompromittiert oder komprimiert** je nach dem was ihre Absicht war

**Comment by phish108** [comment]
kompromittiert
